### ISSUE TITLE
README.md docker run error

### ISSUE THREAD

**Issue by serialt** [soulteary/mini-shortener#1]
docker run -d -v `pwd`/rules:/app/rules -p 8080:8901 soulteary/mini-shortener

**Comment by soulteary** [comment]
> docker run -d -v `pwd`/rules:/app/rules -p 8080:8901 soulteary/mini-shortener

Thanks for the feedback, maybe I should note in the documentation that I need to create a rules file first. @serialt

**Comment by soulteary** [comment]
the version v1.1.0, when a rules file is not found locally, a sample file is created. 

https://github.com/soulteary/mini-shortener/releases/tag/v1.1.0

cc @serialt
